import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { Provider } from '@/components/ui/provider';
import './global.css';

export const metadata = {
  title: 'Welcome to i-took-it-personal',
  description: 'Generated by create-nx-workspace',
};

const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <QueryClientProvider client={queryClient}>
          <Provider>{children}</Provider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
